-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 20:21:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema herbalife_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `herbalife_dev` ;

-- -----------------------------------------------------
-- Schema herbalife_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `herbalife_dev` DEFAULT CHARACTER SET latin1 ;
USE `herbalife_dev` ;

-- -----------------------------------------------------
-- Table `herbalife_dev`.`ci_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`ci_settings` (
  `id_setting` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  `tabla` VARCHAR(250) NOT NULL COMMENT '{\"label\":\"Tabla\",\"input\":\"select\",\"options\":\"db_tabs\"}',
  `id_field` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"label\":\"Columna Referencia\",\"validate\":0,\"input\":\"select\",\"class\":\"table-ref\"}',
  `fields` VARCHAR(800) NULL DEFAULT NULL COMMENT '{\"validate\":0,\"label\":\"Columnas\",\"input\":\"multiselect\",\"class\":\"table-fields\"}',
  `edit_tag` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  `date_created` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_setting`),
  CONSTRAINT `ci_settings_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_settings_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1
COMMENT = '{\"title\":\"Configuraciones del Sistema\",\"indexFields\":[\"id_setting\",\"tabla\",\"nombre\",\"descripcion\"]}';

CREATE INDEX `ci_settings_ibfk_1` ON `herbalife_dev`.`ci_settings` (`id_user_created` ASC);

CREATE INDEX `ci_settings_ibfk_2` ON `herbalife_dev`.`ci_settings` (`id_user_modified` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`ci_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`ci_options` (
  `id_option` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `id_setting` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Opcion para\",\"input\":\"dropdown\",\"selectBy\":[\"nombre\"]}',
  `nivel` VARCHAR(200) NULL DEFAULT NULL COMMENT '{\"label\":\"Nivel de usuario\",\"input\":\"radios\",\"options\":[\"Baja\",\"Media\",\"Alta\"]}',
  `precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `num_fichas` INT(11) NULL DEFAULT NULL,
  `id_modulo` INT(11) NULL DEFAULT NULL,
  `edit_tag` VARCHAR(250) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NULL DEFAULT '0',
  `id_user_modified` INT(10) UNSIGNED NOT NULL,
  `id_user_created` INT(10) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_option`),
  CONSTRAINT `ci_options_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_options_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_options_ibfk_3`
    FOREIGN KEY (`id_setting`)
    REFERENCES `herbalife_dev`.`ci_settings` (`id_setting`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1
COMMENT = '{\"title\":\"Opciones del Sistema\",\n\"listedFields\":[\"nombre\",\"descripcion\",\"id_setting\"],\n\"id_setting\":{\n\"edit-roles\":[\"id_setting\",\"nombre\",\"descripcion\",\"nivel\",\"tipo\",\"edit_tag\"],\n\"edit-prepagos\":[\"id_setting\",\"nombre\",\"descripcion\",\"precio\",\"num_fichas\",\"tipo\"],\n\"edit-modulos\":[\"id_setting\",\"id_modulo\",\"nombre\",\"descripcion\",\"tipo\"],\n\"edit-tipo_asociado\":[\"id_setting\",\"nombre\",\"descripcion\",\"tipo\"],\n\"edit-nivel_asociado\":[\"id_setting\",\"nombre\",\"descripcion\",\"tipo\"],\n\"edit-tipo_usuario\":[\"id_setting\",\"nombre\",\"descripcion\",\"tipo\",\"edit_tag\"],\n\"edit-tipo_producto\":[\"id_setting\",\"nombre\",\"descripcion\",\"tipo\"],\n\"edit-categoria_producto\":[\"id_setting\",\"nombre\",\"descripcion\",\"tipo\"]\n}}';

CREATE INDEX `hbf_opciones_ibfk_1` ON `herbalife_dev`.`ci_options` (`id_user_created` ASC);

CREATE INDEX `hbf_opciones_ibfk_2` ON `herbalife_dev`.`ci_options` (`id_user_modified` ASC);

CREATE INDEX `ci_options_ibfk_3` ON `herbalife_dev`.`ci_options` (`id_setting` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_clubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_clubs` (
  `id_club` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `licencia` VARCHAR(100) NOT NULL,
  `direccion_gps` VARCHAR(100) NOT NULL COMMENT '{\"validate\":0,\"input\":\"hidden\"}',
  `ids_miembros` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"label\":\"Agregar Miembros\",\"input\":\"button\",\"subTable\":\"hbf_usuarios\",\"subview\":\"edit-ini\",\n\"action\":\"edit\",\"onclick\":\"oModal.open(this)\",\"content\":\"Haz click para agregar nuevos miembros\",\"validate\":0}',
  `ids_turnos` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"label\":\"Agregar Turnos\",\"input\":\"button\",\"subTable\":\"hbf_turnos\",\"action\":\"edit\",\"onclick\":\"oModal.open(this)\",\"content\":\"Haz click para agregar nuevos turnos\",\"validate\":0}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL COMMENT '{\"selectBy\":[\"nombre\",\"apellido\"],\"input\":\"multiselect\",\"label\":\"Ususario que modifico\"}',
  `id_user_created` INT(11) UNSIGNED NOT NULL COMMENT '{\"selectBy\":[\"nombre\",\"apellido\"],\"input\":\"multiselect\",\"label\":\"Ususario que creo\"}',
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_club`),
  CONSTRAINT `hbf_clubs_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_clubs_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `hbf_clubs_ibfk_2` ON `herbalife_dev`.`hbf_clubs` (`id_user_modified` ASC);

CREATE INDEX `hbf_clubs_ibfk_3` ON `herbalife_dev`.`hbf_clubs` (`id_user_created` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_turnos` (
  `id_turno` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_club` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Nombre del Club\",\"input\":\"dropdown\",\"selectBy\":\"nombre\"}',
  `id_asociado` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Asociado a cargo\",\"input\":\"dropdown\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `fec_inicio` DATE NOT NULL COMMENT '{\"label\":\"Fecha de Inicio\",\"validate\":0}',
  `fec_fin` DATE NULL DEFAULT NULL COMMENT '{\"label\":\"Fecha de Cierre\",\"validate\":0}',
  `horario_desde` TIME NOT NULL COMMENT '{\"label\":\"hora de inicio\",\"validate\":0}',
  `horario_hasta` TIME NOT NULL COMMENT '{\"label\":\"Hora de Cierre\",\"validate\":0}',
  `total_consumos` INT(11) NOT NULL DEFAULT '0' COMMENT '{\"label\":\"Total de consumos\",\"validate\":0}',
  `id_opcion_turnos` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Turno con\",\"input\":\"select\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":10,\"0\":\"nombre\"}}',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_turno`),
  CONSTRAINT `hbf_turnos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_turnos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_turnos_ibfk_3`
    FOREIGN KEY (`id_asociado`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_turnos_ibfk_4`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`),
  CONSTRAINT `hbf_turnos_ibfk_5`
    FOREIGN KEY (`id_opcion_turnos`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = '{\"id_opcion_turnos\":{\"edit-ini\":[\"fec_inicio\"]}}';

CREATE INDEX `id_asociado` ON `herbalife_dev`.`hbf_turnos` (`id_asociado` ASC);

CREATE INDEX `id_club` ON `herbalife_dev`.`hbf_turnos` (`id_club` ASC);

CREATE INDEX `id_user_modified` ON `herbalife_dev`.`hbf_turnos` (`id_user_modified` ASC);

CREATE INDEX `id_user_created` ON `herbalife_dev`.`hbf_turnos` (`id_user_created` ASC);

CREATE INDEX `hbf_turnos_ibfk_5` ON `herbalife_dev`.`hbf_turnos` (`id_opcion_turnos` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_sesiones` (
  `id_sesion` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_club` INT(11) UNSIGNED NOT NULL COMMENT '{\"label\":\"Nombre del club\",\"input\":\"select\",\"selectBy\":\"nombre\"}',
  `id_turno` INT(11) UNSIGNED NOT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"default\",\"selectBy\":\"id_asociado\"}',
  `id_asociado` INT(11) UNSIGNED NOT NULL COMMENT '{\"label\":\"Sesion a cargo de\",\"input\":\"default\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `detalle` VARCHAR(400) NULL DEFAULT '',
  `caja_inicial` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Monto inicial en caja\"}',
  `caja_final` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Monto final en caja\"}',
  `total` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Monto total en caja\"}',
  `num_consumos` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Cantidad de consumos del dia\"}',
  `total_ingresos` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Total ingresos\"}',
  `total_egresos` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Total egresos\"}',
  `total_deben` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Total deudas de clientes\"}',
  `total_sobra` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Total dinero sobrante\"}',
  `total_falta` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Total dinero faltante\"}',
  `sobre_rojo` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Dinero al sobre rojo\"}',
  `sobre_verde` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Dinero al sobre verde\"}',
  `deposito` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Dinero depositado\"}',
  `cerrado` VARCHAR(10) NULL DEFAULT NULL COMMENT '{\"label\":\"Estado de la sesion\",\"input\":\"radios\",\"options\":[\"cerrado\",\"abierto\"]}',
  `observaciones` VARCHAR(400) NULL DEFAULT '',
  `fec_sesion` DATETIME NULL DEFAULT NULL,
  `id_opcion_sesion` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Sesion con\",\"input\":\"select\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":9,\"0\":\"nombre\"}}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_sesion`),
  CONSTRAINT `hbf_sesiones_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_sesiones_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_sesiones_ibfk_3`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`),
  CONSTRAINT `hbf_sesiones_ibfk_4`
    FOREIGN KEY (`id_asociado`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_sesiones_ibfk_5`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`),
  CONSTRAINT `hbf_sesiones_ibfk_6`
    FOREIGN KEY (`id_opcion_sesion`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = '{\"id_opcion_sesion\":{\"edit-ini\":[\"fec_sesion\",\"caja_inicial\"]}}';

CREATE INDEX `id_encargado` ON `herbalife_dev`.`hbf_sesiones` (`id_asociado` ASC);

CREATE INDEX `id_club` ON `herbalife_dev`.`hbf_sesiones` (`id_club` ASC);

CREATE INDEX `id_turno` ON `herbalife_dev`.`hbf_sesiones` (`id_turno` ASC);

CREATE INDEX `id_user_modified` ON `herbalife_dev`.`hbf_sesiones` (`id_user_modified` ASC);

CREATE INDEX `id_user_created` ON `herbalife_dev`.`hbf_sesiones` (`id_user_created` ASC);

CREATE INDEX `hbf_sesiones_ibfk_6` ON `herbalife_dev`.`hbf_sesiones` (`id_opcion_sesion` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`ci_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`ci_usuarios` (
  `id_usuario` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NULL DEFAULT NULL,
  `apellido` VARCHAR(256) NULL DEFAULT NULL,
  `username` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '{\"validate\":[\"email\"]}',
  `password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '{\"validate\":[\"password\"],\"input\":\"password\"}',
  `fec_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(15) NULL DEFAULT NULL COMMENT '{\"input\":\"radios\",\"options\":[\"Masculino\",\"Femenino\"]}',
  `invitado_por` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Invitado por\",\"input\":\"dropdown\",\"selectBy\":[\"nombre\",\"apellido\"],\"validate\":0}',
  `phone_number_1` VARCHAR(20) NULL DEFAULT NULL COMMENT '{\"label\":\"Telefono 1\"}',
  `phone_number_2` VARCHAR(20) NULL DEFAULT NULL COMMENT '{\"labe\":\"Telefono 2\"}',
  `cellphone_number_1` VARCHAR(20) NULL DEFAULT NULL COMMENT '{\"label\":\"Celular 1\"}',
  `cellphone_number_2` VARCHAR(20) NULL DEFAULT NULL COMMENT '{\"label\":\"Celular 2\"}',
  `cod_acceso` VARCHAR(50) NULL DEFAULT NULL COMMENT '{\"label\":\"Codigo de acceso\"}',
  `id_option_tipo_asociado` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Tipo de asociado\",\"input\":\"dropdown\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":2,\"0\":\"nombre\"}}',
  `id_option_nivel_asociado` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Nivel de asociado\",\"input\":\"dropdown\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":3,\"0\":\"nombre\"}}',
  `id_club` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Club Perteneciente\",\"input\":\"select\",\"selectBy\":[\"nombre\"]}',
  `id_turno` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"dropdown\",\"selectBy\":\"id_asociado\"}',
  `id_sesion` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Sesion de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_opcion_role` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Role del usuario\",\"input\":\"radios\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":4,\"0\":\"nombre\"}}',
  `foto_perfil` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Foto de perfil\",\"input\":\"image\",\"validate\":0}',
  `app_monitor` VARCHAR(50) NULL DEFAULT NULL COMMENT '{\"label\":\"Permitir app monitoreo\",\"input\":\"radios\",\"options\":[\"SI\",\"NO\"]}',
  `app_orders` VARCHAR(50) NULL DEFAULT NULL COMMENT '{\"label\":\"Permitir app ordenes\",\"input\":\"radios\",\"options\":[\"SI\",\"NO\"]}',
  `app_admin` VARCHAR(50) NULL DEFAULT NULL COMMENT '{\"label\":\"Permitir app administrador\",\"input\":\"radios\",\"options\":[\"SI\",\"NO\"]}',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `herbalife_key` VARCHAR(256) NULL DEFAULT NULL,
  `id_tipo_usuario` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Tipo de Usuario\",\"input\":\"radios\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":5,\"0\":\"nombre\"}}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `ci_usuarios_ibfk_1`
    FOREIGN KEY (`id_option_tipo_asociado`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `ci_usuarios_ibfk_2`
    FOREIGN KEY (`id_option_nivel_asociado`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `ci_usuarios_ibfk_3`
    FOREIGN KEY (`invitado_por`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_usuarios_ibfk_4`
    FOREIGN KEY (`id_opcion_role`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `ci_usuarios_ibfk_5`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`),
  CONSTRAINT `ci_usuarios_ibfk_6`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`),
  CONSTRAINT `ci_usuarios_ibfk_7`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `ci_usuarios_ibfk_8`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COMMENT = '{\"indexFields\":[\"nombre\",\"apellido\",\"sexo\",\"cellphone_number_1\"],\"numListed\":5,\n\"id_tipo_usuario\":{\n\"edit-draft\":[\"nombre\",\"apellido\",\"sexo\",\"id_option_tipo_usuario\"],\n\"edit-cliente\":[\"nombre\",\"apellido\",\"sexo\",\"cellphone_number_1\",\"id_turno\",\"id_sesion\",\"foto_perfil\",\"id_option_tipo_usuario\"],\n\"edit-ini\":[\"nombre\",\"apellido\",\"sexo\",\"cellphone_number_1\",\"id_option_tipo_usuario\"]\n}}';

CREATE INDEX `ci_usuarios_ibfk_3` ON `herbalife_dev`.`ci_usuarios` (`invitado_por` ASC);

CREATE INDEX `ci_usuarios_ibfk_5` ON `herbalife_dev`.`ci_usuarios` (`id_turno` ASC);

CREATE INDEX `ci_usuarios_ibfk_6` ON `herbalife_dev`.`ci_usuarios` (`id_sesion` ASC);

CREATE INDEX `ci_usuarios_ibfk_1` ON `herbalife_dev`.`ci_usuarios` (`id_option_tipo_asociado` ASC);

CREATE INDEX `ci_usuarios_ibfk_2` ON `herbalife_dev`.`ci_usuarios` (`id_option_nivel_asociado` ASC);

CREATE INDEX `ci_usuarios_ibfk_4` ON `herbalife_dev`.`ci_usuarios` (`id_opcion_role` ASC);

CREATE INDEX `ci_usuarios_ibfk_7` ON `herbalife_dev`.`ci_usuarios` (`id_tipo_usuario` ASC);

CREATE INDEX `ci_usuarios_ibfk_8` ON `herbalife_dev`.`ci_usuarios` (`id_club` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`ci_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`ci_modulos` (
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `id_opcion_modulo` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Modulo\",\"input\":\"select\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":1,\"0\":\"nombre\"}}',
  `id_opcion_roles` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Role Admitido\",\"input\":\"select\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":4,\"0\":\"nombre\"}}',
  `titulo` VARCHAR(100) NOT NULL,
  `tabla` VARCHAR(255) NULL DEFAULT NULL,
  `listed` VARCHAR(15) NOT NULL DEFAULT 'ENABLED' COMMENT '{\"input\":\"radio\",\"options\":[\"ENABLED\",\"DISABLED\"]}',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `icon` VARCHAR(200) NOT NULL COMMENT '{\"validate\":0}',
  `url` VARCHAR(600) NOT NULL,
  `estado` VARCHAR(255) NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_modulo`),
  CONSTRAINT `ci_modulos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_modulos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_modulos_ibfk_3`
    FOREIGN KEY (`id_opcion_modulo`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `ci_modulos_ibfk_4`
    FOREIGN KEY (`id_opcion_roles`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `id_user_modified` ON `herbalife_dev`.`ci_modulos` (`id_user_modified` ASC);

CREATE INDEX `id_user_created` ON `herbalife_dev`.`ci_modulos` (`id_user_created` ASC);

CREATE INDEX `ci_modulos_ibfk_3` ON `herbalife_dev`.`ci_modulos` (`id_opcion_modulo` ASC);

CREATE INDEX `ci_modulos_ibfk_4` ON `herbalife_dev`.`ci_modulos` (`id_opcion_roles` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`ci_sessions` (
  `id` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL COMMENT '{\"label\":\"Datos en sesion\",\"input\":\"textarea\"}',
  `last_activity` DATETIME NOT NULL,
  `id_usuario` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Nombre del Usuario\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `id_hbf_sesion` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Sesion de\",\"selectBy\":\"id_asociado\"}',
  PRIMARY KEY (`id`),
  CONSTRAINT `ci_sessions_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `ci_sessions_ibfk_2`
    FOREIGN KEY (`id_hbf_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '{\"title\":\"Sesiones del Sistema\",\"indexFields\":[\"ip_address\",\"timestamp\",\"last_activity\",\"id_usuario\"],\"numListed\":4}';

CREATE INDEX `ci_sessions_ibfk_1` ON `herbalife_dev`.`ci_sessions` (`id_usuario` ASC);

CREATE INDEX `id_hbf_sesion` ON `herbalife_dev`.`ci_sessions` (`id_hbf_sesion` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_prepagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_prepagos` (
  `id_prepago` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Cliente\",\"input\":\"dropdown\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `id_turno` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_sesion` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Sesion de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `fichas_total` INT(11) NULL DEFAULT NULL,
  `fichas_usadas` INT(11) NULL DEFAULT NULL,
  `fichas_gratis` INT(11) NULL DEFAULT NULL,
  `fichas_restantes` INT(11) NULL DEFAULT NULL,
  `id_option_tipo_prepago` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Tipo de Prepago\",\"input\":\"select\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":5,\"0\":\"nombre\"}}',
  `a_cuenta` DECIMAL(10,0) NULL DEFAULT NULL,
  `saldo` DECIMAL(10,0) NULL DEFAULT NULL,
  `importe` DECIMAL(10,0) NULL DEFAULT NULL,
  `pagado` VARCHAR(50) NULL DEFAULT 'NO' COMMENT '{\"options\":[\"SI\",\"NO\"],\"input\":\"radios\"}',
  `finalizado` VARCHAR(50) NULL DEFAULT 'NO' COMMENT '{\"options\":[\"SI\",\"NO\"],\"input\":\"radios\"}',
  `observaciones` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_prepago`),
  CONSTRAINT `hbf_prepagos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_prepagos_ibfk_2`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_prepagos_ibfk_3`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_prepagos_ibfk_4`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`),
  CONSTRAINT `hbf_prepagos_ibfk_5`
    FOREIGN KEY (`id_option_tipo_prepago`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `hbf_prepagos_ibfk_6`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `hbf_prepago_ibfk_1` ON `herbalife_dev`.`hbf_prepagos` (`id_cliente` ASC);

CREATE INDEX `hbf_prepago_ibfk_2` ON `herbalife_dev`.`hbf_prepagos` (`id_user_modified` ASC);

CREATE INDEX `hbf_prepago_ibfk_3` ON `herbalife_dev`.`hbf_prepagos` (`id_user_created` ASC);

CREATE INDEX `hbf_prepago_ibfk_5` ON `herbalife_dev`.`hbf_prepagos` (`id_option_tipo_prepago` ASC);

CREATE INDEX `hbf_prepago_ibfk_6` ON `herbalife_dev`.`hbf_prepagos` (`id_turno` ASC);

CREATE INDEX `hbf_prepagos_ibfk_4` ON `herbalife_dev`.`hbf_prepagos` (`id_sesion` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_comandas` (
  `id_comanda` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_club` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Nombre del Club\",\"input\":\"select\",\"selectBy\":\"nombre\"}',
  `id_turno` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\",\"descripcion\"]}',
  `id_sesion` INT(11) UNSIGNED NOT NULL COMMENT '{\"label\":\"Sesion de\",\"input\":\"select\",\"selectBy\":\"id_asociado\"}',
  `id_cliente` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Nombre del Cliente\",\"input\":\"default\",\"selectBy\":[\"nombre\",\"apellido\"],\"button\":{\"content\":\"Nuevo Cliente\",\"action\":\"edit\",\"subTable\":\"ci_usuarios\",\"subView\":\"draft\",\"onclick\":\"oModal.open(this)\"}}',
  `ids_vasos` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"label\":\"Agregar Vasos\",\"input\":\"button\",\"subTable\":\"hbf_vasos\",\"action\":\"edit\",\"onclick\":\"oCrud.save(this,oModal.open)\",\"content\":\"Haz click para agregar vasos\",\"validate\":0}',
  `importe` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `a_cuenta` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `saldo` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `prioridad` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"label\":\"Prioridad\",\"input\":\"radios\",\"options\":[\"programada\",\"normal\",\"rapida\"],\"validate\":0}',
  `hora_entrega` TIME NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `tipo_consumo` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"label\":\"Tipo de Consumo\",\"input\":\"select\",\"options\":[\"Socio\",\"Estudiante\"]}',
  `comentarios` TEXT NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `id_ficha_prepago` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Ficha Prepago\",\"input\":\"select\",\"selectBy\":\"id_cliente\",\"validate\":0}',
  `pagado` VARCHAR(10) NULL DEFAULT NULL COMMENT '{\"label\":\"Estado de la comanda\",\"input\":\"radios\",\"options\":[\"debe\",\"pagado\"],\"validate\":0}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_comanda`),
  CONSTRAINT `hbf_comandas_ibfk_1`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hbf_comandas_ibfk_2`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hbf_comandas_ibfk_3`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`),
  CONSTRAINT `hbf_comandas_ibfk_4`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_comandas_ibfk_5`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_comandas_ibfk_6`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_comandas_ibfk_8`
    FOREIGN KEY (`id_ficha_prepago`)
    REFERENCES `herbalife_dev`.`hbf_prepagos` (`id_prepago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `hbf_comandas_ibfk_1` ON `herbalife_dev`.`hbf_comandas` (`id_club` ASC);

CREATE INDEX `hbf_comandas_ibfk_2` ON `herbalife_dev`.`hbf_comandas` (`id_turno` ASC);

CREATE INDEX `hbf_comandas_ibfk_3` ON `herbalife_dev`.`hbf_comandas` (`id_sesion` ASC);

CREATE INDEX `hbf_comandas_ibfk_5` ON `herbalife_dev`.`hbf_comandas` (`id_cliente` ASC);

CREATE INDEX `hbf_comandas_ibfk_6` ON `herbalife_dev`.`hbf_comandas` (`id_user_modified` ASC);

CREATE INDEX `hbf_comandas_ibfk_7` ON `herbalife_dev`.`hbf_comandas` (`id_user_created` ASC);

CREATE INDEX `hbf_comandas_ibfk_8` ON `herbalife_dev`.`hbf_comandas` (`id_ficha_prepago` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_productos` (
  `id_producto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL COMMENT '{\"validate\":0}',
  `id_option_tipo_producto` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Tipos de Productos\",\"input\":\"dropdown\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":6,\"0\":\"nombre\"}}',
  `id_option_categoria_producto` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Categorias de Productos\",\"input\":\"dropdown\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":7,\"0\":\"nombre\"}}',
  `foto_producto` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"label\":\"Imagen del producto\",\"input\":\"image\", \"validate\":0}',
  `precio_venta` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Precio de ventra\"}',
  `precio_porcion` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Precio de una porcion\"}',
  `precio_compra` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '{\"label\":\"Precio de Compra\"}',
  `num_porciones` INT(11) NULL DEFAULT '0' COMMENT '{\"label\":\"Numero de Porciones\"}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NULL DEFAULT NULL,
  `date_created` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `hbf_productos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_productos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_productos_ibfk_3`
    FOREIGN KEY (`id_option_categoria_producto`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`),
  CONSTRAINT `hbf_productos_ibfk_4`
    FOREIGN KEY (`id_option_tipo_producto`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `hbf_productos_ibfk_1` ON `herbalife_dev`.`hbf_productos` (`id_user_modified` ASC);

CREATE INDEX `hbf_productos_ibfk_2` ON `herbalife_dev`.`hbf_productos` (`id_user_created` ASC);

CREATE INDEX `hbf_productos_ibfk_3` ON `herbalife_dev`.`hbf_productos` (`id_option_categoria_producto` ASC);

CREATE INDEX `hbf_productos_ibfk_4` ON `herbalife_dev`.`hbf_productos` (`id_option_tipo_producto` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_vasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_vasos` (
  `id_vaso` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_comanda` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Comanda del Cliente\",\"input\":\"select\",\"selectBy\":[\"id_cliente\"]}',
  `nivel` INT(11) NULL DEFAULT NULL COMMENT '{\"label\":\"Nivel del vaso (0% - 100%)\"}',
  `temperatura` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"label\":\"Temperatura\",\"options\":[\"Frio\",\"Tibio\",\"Caliente\"],\"input\":\"radios\"}',
  `consistencia` VARCHAR(250) NULL DEFAULT NULL COMMENT '{\"label\":\"Consistencia\",\"options\":[\"Cremoso\",\"Al jugo\"],\"input\":\"radios\"}',
  `id_opcion_tipo_producto` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Tipos de Productos\",\"input\":\"radios\",\"selectBy\":[\"id_setting\"],\"filterBy\":{\"id_setting\":6,\"0\":\"nombre\"},\n\"subTable\":\"hbf_detalles_pedidos\",\"action\":\"edit\",\"onclick\":\"oModal.open(this)\"}',
  `num_productos` INT(11) NULL DEFAULT '0' COMMENT '{\"label\":\"Numero de Productos\",\"validate\":0,\"data\":{\"step\":1}}',
  `detalle` VARCHAR(500) NULL DEFAULT NULL COMMENT '{\"validate\":0}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_vaso`),
  CONSTRAINT `hbf_vasos_ibfk_1`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hbf_vasos_ibfk_2`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hbf_vasos_ibfk_3`
    FOREIGN KEY (`id_comanda`)
    REFERENCES `herbalife_dev`.`hbf_comandas` (`id_comanda`),
  CONSTRAINT `hbf_vasos_ibfk_4`
    FOREIGN KEY (`id_opcion_tipo_producto`)
    REFERENCES `herbalife_dev`.`ci_options` (`id_option`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `hbf_vasos_ibfk_1` ON `herbalife_dev`.`hbf_vasos` (`id_user_modified` ASC);

CREATE INDEX `hbf_vasos_ibfk_2` ON `herbalife_dev`.`hbf_vasos` (`id_user_created` ASC);

CREATE INDEX `hbf_vasos_ibfk_3` ON `herbalife_dev`.`hbf_vasos` (`id_comanda` ASC);

CREATE INDEX `hbf_vasos_ibfk_4` ON `herbalife_dev`.`hbf_vasos` (`id_opcion_tipo_producto` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_detalles_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_detalles_pedidos` (
  `id_detalle_pedido` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_comanda` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Comanda del Cliente\",\"input\":\"select\",\"selectBy\":[\"id_cliente\"]}',
  `id_vaso` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Vaso del Cliente\",\"input\":\"select\",\"selectBy\":[\"id_comanda\"]}',
  `id_producto` INT(10) UNSIGNED NOT NULL COMMENT '{\"label\":\"Producto\",\"input\":\"checkbox\",\"selectBy\":[\"nombre\",\"foto_producto\",[\"id_option_tipo_producto\"]],\"divider\":\"|\",\"insertEachOne\":true}',
  `cantidad` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  CONSTRAINT `hbf_detalles_pedidos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_detalles_pedidos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_detalles_pedidos_ibfk_4`
    FOREIGN KEY (`id_producto`)
    REFERENCES `herbalife_dev`.`hbf_productos` (`id_producto`),
  CONSTRAINT `hbf_detalles_pedidos_ibfk_5`
    FOREIGN KEY (`id_vaso`)
    REFERENCES `herbalife_dev`.`hbf_vasos` (`id_vaso`),
  CONSTRAINT `hbf_detalles_pedidos_ibfk_6`
    FOREIGN KEY (`id_comanda`)
    REFERENCES `herbalife_dev`.`hbf_comandas` (`id_comanda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '{\"title\":\"Detalles de Pedidos\"}';

CREATE INDEX `id_user_modified` ON `herbalife_dev`.`hbf_detalles_pedidos` (`id_user_modified` ASC);

CREATE INDEX `id_user_created` ON `herbalife_dev`.`hbf_detalles_pedidos` (`id_user_created` ASC);

CREATE INDEX `id_vaso` ON `herbalife_dev`.`hbf_detalles_pedidos` (`id_vaso` ASC);

CREATE INDEX `hbf_detalles_pedidos_ibfk_4` ON `herbalife_dev`.`hbf_detalles_pedidos` (`id_producto` ASC);

CREATE INDEX `id_comanda` ON `herbalife_dev`.`hbf_detalles_pedidos` (`id_comanda` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_egresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_egresos` (
  `id_egreso` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_club` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Club de\",\"input\":\"select\",\"selectBy\":[\"nombre\"]}',
  `id_turno` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_sesion` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Sesion de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_cliente` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Cliente\",\"input\":\"default\",\"selectBy\":[\"nombre\"],\"validate\":0}',
  `detalle` VARCHAR(500) NULL DEFAULT NULL,
  `tipo_egreso` VARCHAR(10) NULL DEFAULT NULL COMMENT '{\"label\":\"Tipo de Egreso\",\"input\":\"select\",\"options\":[\"Gastos\",\"Costos\"]}',
  `fecha_egreso` DATE NULL DEFAULT NULL,
  `monto` DECIMAL(10,0) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_egreso`),
  CONSTRAINT `hbf_egresos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_egresos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_egresos_ibfk_3`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_egresos_ibfk_4`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`),
  CONSTRAINT `hbf_egresos_ibfk_5`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`),
  CONSTRAINT `hbf_egresos_ibfk_6`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `hbf_egresos_id_egreso_uindex` ON `herbalife_dev`.`hbf_egresos` (`id_egreso` ASC);

CREATE INDEX `hbf_egresos_ibfk_1` ON `herbalife_dev`.`hbf_egresos` (`id_user_created` ASC);

CREATE INDEX `hbf_egresos_ibfk_2` ON `herbalife_dev`.`hbf_egresos` (`id_user_modified` ASC);

CREATE INDEX `hbf_egresos_ibfk_3` ON `herbalife_dev`.`hbf_egresos` (`id_cliente` ASC);

CREATE INDEX `hbf_egresos_ibfk_4` ON `herbalife_dev`.`hbf_egresos` (`id_turno` ASC);

CREATE INDEX `hbf_egresos_ibfk_5` ON `herbalife_dev`.`hbf_egresos` (`id_sesion` ASC);

CREATE INDEX `hbf_egresos_ibfk_6` ON `herbalife_dev`.`hbf_egresos` (`id_club` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_ingresos` (
  `id_ingreso` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Nombre del Cliente\",\"input\":\"default\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `id_comanda` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Comanda\",\"input\":\"dropdown\",\"selectBy\":[\"id_cliente\"]}',
  `id_prepago` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Prepago\",\"input\":\"dropdown\",\"selectBy\":[\"id_cliente\"]}',
  `id_producto` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Producto\",\"input\":\"dropdown\",\"selectBy\":[\"nombre\",\"descripcion\"]}',
  `estado` VARCHAR(15) NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(10) UNSIGNED NOT NULL,
  `id_user_created` INT(10) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_ingreso`),
  CONSTRAINT `hbf_ingresos_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ingresos_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ingresos_ibfk_3`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ingresos_ibfk_4`
    FOREIGN KEY (`id_producto`)
    REFERENCES `herbalife_dev`.`hbf_productos` (`id_producto`),
  CONSTRAINT `hbf_ingresos_ibfk_5`
    FOREIGN KEY (`id_comanda`)
    REFERENCES `herbalife_dev`.`hbf_comandas` (`id_comanda`),
  CONSTRAINT `hbf_ingresos_ibfk_6`
    FOREIGN KEY (`id_prepago`)
    REFERENCES `herbalife_dev`.`hbf_prepagos` (`id_prepago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `hbf_ingresos_ibfk_3` ON `herbalife_dev`.`hbf_ingresos` (`id_cliente` ASC);

CREATE INDEX `hbf_ingresos_ibfk_5` ON `herbalife_dev`.`hbf_ingresos` (`id_comanda` ASC);

CREATE INDEX `hbf_ingresos_ibfk_6` ON `herbalife_dev`.`hbf_ingresos` (`id_prepago` ASC);

CREATE INDEX `hbf_ingresos_ibfk_4` ON `herbalife_dev`.`hbf_ingresos` (`id_producto` ASC);

CREATE INDEX `hbf_ingresos_ibfk_1` ON `herbalife_dev`.`hbf_ingresos` (`id_user_modified` ASC);

CREATE INDEX `hbf_ingresos_ibfk_2` ON `herbalife_dev`.`hbf_ingresos` (`id_user_created` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_porciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_porciones` (
  `id_porcion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_producto` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Productos\",\"input\":\"checkbox\",\"selectBy\":[\"nombre\",\"foto_producto\"],\"divider\":\"|\",\"insertEachOne\":true}',
  `cantidad` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id_porcion`),
  CONSTRAINT `hbf_porciones_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_porciones_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_porciones_ibfk_3`
    FOREIGN KEY (`id_producto`)
    REFERENCES `herbalife_dev`.`hbf_productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `hbf_porsiones_ibfk_1` ON `herbalife_dev`.`hbf_porciones` (`id_user_created` ASC);

CREATE INDEX `hbf_porsiones_ibfk_2` ON `herbalife_dev`.`hbf_porciones` (`id_user_modified` ASC);

CREATE INDEX `hbf_porsiones_ibfk_3` ON `herbalife_dev`.`hbf_porciones` (`id_producto` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`hbf_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`hbf_ventas` (
  `id_venta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_club` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Club\",\"input\":\"select\",\"selectBy\":[\"nombre\"]}',
  `id_turno` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Turno de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_sesion` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Sesion de\",\"input\":\"select\",\"selectBy\":[\"id_asociado\"]}',
  `id_cliente` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Cliente\",\"input\":\"select\",\"selectBy\":[\"nombre\",\"apellido\"]}',
  `fecha_venta` DATE NULL DEFAULT NULL,
  `id_producto` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '{\"label\":\"Producto\",\"input\":\"multiselect\",\"selectBy\":[\"nombre\",\"foto_producto\"]}',
  `precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `observaciones` VARCHAR(600) NULL DEFAULT NULL,
  `a_cuenta` DECIMAL(10,0) NULL DEFAULT NULL,
  `saldo` DECIMAL(10,0) NULL DEFAULT NULL,
  `entregado` VARCHAR(10) NULL DEFAULT NULL COMMENT '{\"label\":\"Fue Entregado?\",\"input\":\"radios\",\"options\":[\"si\",\"no\"]}',
  `pagado` VARCHAR(10) NULL DEFAULT NULL COMMENT '{\"label\":\"Fue Pagado?\",\"input\":\"radios\",\"options\":[\"si\",\"no\"]}',
  `estado` VARCHAR(15) NOT NULL DEFAULT 'ENABLED',
  `change_count` INT(11) NOT NULL DEFAULT '0',
  `id_user_modified` INT(11) UNSIGNED NOT NULL,
  `id_user_created` INT(11) UNSIGNED NOT NULL,
  `date_modified` INT(11) NOT NULL,
  `date_created` INT(11) NOT NULL,
  PRIMARY KEY (`id_venta`),
  CONSTRAINT `hbf_ventas_ibfk_1`
    FOREIGN KEY (`id_user_created`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ventas_ibfk_2`
    FOREIGN KEY (`id_user_modified`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ventas_ibfk_3`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `herbalife_dev`.`ci_usuarios` (`id_usuario`),
  CONSTRAINT `hbf_ventas_ibfk_4`
    FOREIGN KEY (`id_club`)
    REFERENCES `herbalife_dev`.`hbf_clubs` (`id_club`),
  CONSTRAINT `hbf_ventas_ibfk_5`
    FOREIGN KEY (`id_turno`)
    REFERENCES `herbalife_dev`.`hbf_turnos` (`id_turno`),
  CONSTRAINT `hbf_ventas_ibfk_6`
    FOREIGN KEY (`id_sesion`)
    REFERENCES `herbalife_dev`.`hbf_sesiones` (`id_sesion`),
  CONSTRAINT `hbf_ventas_ibfk_7`
    FOREIGN KEY (`id_producto`)
    REFERENCES `herbalife_dev`.`hbf_productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `hbf_ventas_id_venta_uindex` ON `herbalife_dev`.`hbf_ventas` (`id_venta` ASC);

CREATE INDEX `hbf_ventas_ibfk_1` ON `herbalife_dev`.`hbf_ventas` (`id_user_created` ASC);

CREATE INDEX `hbf_ventas_ibfk_2` ON `herbalife_dev`.`hbf_ventas` (`id_user_modified` ASC);

CREATE INDEX `hbf_ventas_ibfk_3` ON `herbalife_dev`.`hbf_ventas` (`id_cliente` ASC);

CREATE INDEX `hbf_ventas_ibfk_4` ON `herbalife_dev`.`hbf_ventas` (`id_club` ASC);

CREATE INDEX `hbf_ventas_ibfk_5` ON `herbalife_dev`.`hbf_ventas` (`id_turno` ASC);

CREATE INDEX `hbf_ventas_ibfk_6` ON `herbalife_dev`.`hbf_ventas` (`id_sesion` ASC);

CREATE INDEX `hbf_ventas_ibfk_7` ON `herbalife_dev`.`hbf_ventas` (`id_producto` ASC);


-- -----------------------------------------------------
-- Table `herbalife_dev`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herbalife_dev`.`migrations` (
  `version` BIGINT(20) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
